services:
  backend:
    build:
      context: ./StockAnalysis
    env_file:
        - StockAnalysis/.env
    ports:
      - "7086:7086"
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
